from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text

BACKEND_ROOT = Path(__file__).resolve().parents[1]

# The revision that first created the snapshots table, before the process and
# network columns existed.
BASELINE_REVISION = "c69cb3ded3fd"


@pytest.fixture
def alembic_config(tmp_path, monkeypatch):
    database = (tmp_path / "migrations.db").as_posix()
    # env.py reads the URL from settings, so pointing the env var at a temp file
    # keeps the real syswatch.db out of the test run.
    monkeypatch.setenv("SYSWATCH_DATABASE_URL", f"sqlite:///{database}")

    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    return config, database


def test_upgrade_creates_the_snapshots_schema(alembic_config):
    config, database = alembic_config

    command.upgrade(config, "head")

    inspector = inspect(create_engine(f"sqlite:///{database}"))
    assert "snapshots" in inspector.get_table_names()

    columns = {column["name"] for column in inspector.get_columns("snapshots")}
    assert columns == {
        "id",
        "host_name",
        "collected_at",
        "cpu_core_count",
        "cpu_usage_percent",
        "mem_total_mb",
        "mem_used_mb",
        "disk_total_gb",
        "disk_free_gb",
        "os_name",
        "os_version",
        "process_count",
        "net_bytes_sent_per_sec",
        "net_bytes_recv_per_sec",
        "process_top",
        "network_interfaces",
    }

    assert [i["name"] for i in inspector.get_indexes("snapshots")] == ["ix_snapshots_collected_at"]
    assert [u["name"] for u in inspector.get_unique_constraints("snapshots")] == [
        "uq_snapshots_host_name_collected_at"
    ]


def test_migrations_match_the_models(alembic_config):
    config, _ = alembic_config
    command.upgrade(config, "head")

    # Fails if the ORM models have changed without a matching migration.
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"Models and migrations have diverged: {exc}")


def test_process_and_network_columns_are_added_to_existing_rows_as_null(alembic_config):
    config, database = alembic_config

    # Stop at the baseline, insert a row the old way, then migrate forward.
    command.upgrade(config, BASELINE_REVISION)

    engine = create_engine(f"sqlite:///{database}")
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO snapshots (host_name, collected_at, cpu_core_count, "
                "cpu_usage_percent, mem_total_mb, mem_used_mb, disk_total_gb, "
                "disk_free_gb, os_name, os_version) VALUES "
                "('devbox', :t, 8, 42.5, 16384, 4096, 512, 120, 'Windows', '11')"
            ),
            {"t": "2026-08-12 11:15:27"},
        )

    command.upgrade(config, "head")

    with engine.connect() as connection:
        row = connection.execute(
            text(
                "SELECT host_name, process_count, net_bytes_recv_per_sec, "
                "process_top, network_interfaces FROM snapshots"
            )
        ).one()

    # The row survives the migration; the new columns are NULL, not rewritten.
    assert row.host_name == "devbox"
    assert row.process_count is None
    assert row.net_bytes_recv_per_sec is None
    assert row.process_top is None
    assert row.network_interfaces is None


def test_downgrade_removes_the_table(alembic_config):
    config, database = alembic_config

    command.upgrade(config, "head")
    command.downgrade(config, "base")

    inspector = inspect(create_engine(f"sqlite:///{database}"))
    assert "snapshots" not in inspector.get_table_names()


# The revision that added the alert tables, one before the seed data.
ALERT_TABLES_REVISION = "c6a63f3f08c6"


def test_default_alert_rules_are_seeded(alembic_config):
    config, database = alembic_config

    command.upgrade(config, "head")

    engine = create_engine(f"sqlite:///{database}")
    with engine.connect() as connection:
        rows = connection.execute(
            text("SELECT name, metric, enabled FROM alert_rules ORDER BY id")
        ).all()

    assert [r.name for r in rows] == [
        "CPU usage high",
        "CPU usage critical",
        "Memory usage high",
        "Disk almost full",
        "Process count high",
        "Network receive rate high",
    ]
    assert all(r.enabled for r in rows)


def test_seed_downgrade_removes_only_the_seeded_rules(alembic_config):
    config, database = alembic_config

    command.upgrade(config, "head")

    engine = create_engine(f"sqlite:///{database}")
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO alert_rules "
                "(name, metric, operator, threshold, severity, enabled, created_at, updated_at) "
                "VALUES ('Mine', 'cpu', 'lt', 5, 'info', 1, '2026-01-01', '2026-01-01')"
            )
        )

    command.downgrade(config, ALERT_TABLES_REVISION)

    with engine.connect() as connection:
        names = connection.execute(text("SELECT name FROM alert_rules")).scalars().all()

    # The user's own rule stays; the seeded ones are gone.
    assert names == ["Mine"]


def test_a_pre_alert_database_gains_the_tables_and_seeds_with_rows_intact(alembic_config):
    config, database = alembic_config

    # A database from before any alert work: the original snapshots schema,
    # with a row in it.
    command.upgrade(config, BASELINE_REVISION)
    engine = create_engine(f"sqlite:///{database}")
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO snapshots (host_name, collected_at, cpu_core_count, "
                "cpu_usage_percent, mem_total_mb, mem_used_mb, disk_total_gb, "
                "disk_free_gb, os_name, os_version) VALUES "
                "('devbox', '2026-08-12 11:15:27', 8, 42.5, 16384, 4096, 512, 120, 'Windows', '11')"
            )
        )

    command.upgrade(config, "head")

    inspector = inspect(engine)
    assert {"alert_rules", "alerts"}.issubset(inspector.get_table_names())

    with engine.connect() as connection:
        rule_count = connection.execute(text("SELECT COUNT(*) FROM alert_rules")).scalar_one()
        snapshot = connection.execute(
            text("SELECT host_name, cpu_usage_percent FROM snapshots")
        ).one()

    assert rule_count == 6
    assert (snapshot.host_name, snapshot.cpu_usage_percent) == ("devbox", 42.5)


def test_seed_upgrade_skips_a_name_that_already_exists(alembic_config):
    config, database = alembic_config

    # Stop just before the seed, plant a rule sharing one of its names.
    command.upgrade(config, ALERT_TABLES_REVISION)

    engine = create_engine(f"sqlite:///{database}")
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO alert_rules "
                "(name, metric, operator, threshold, severity, enabled, created_at, updated_at) "
                "VALUES ('Disk almost full', 'disk', 'lt', 1, 'critical', 0, '2026-01-01', '2026-01-01')"
            )
        )

    command.upgrade(config, "head")

    with engine.connect() as connection:
        rows = connection.execute(
            text("SELECT threshold, severity FROM alert_rules WHERE name = 'Disk almost full'")
        ).all()

    # Not duplicated, and the existing row is left as the user had it.
    assert rows == [(1.0, "critical")]
