from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect

BACKEND_ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture
def alembic_config(tmp_path, monkeypatch):
    database = (tmp_path / "migrations.db").as_posix()
    # env.py reads the URL from settings, so pointing the env var at a temp file
    # keeps the real syswatch.db out of the test run.
    monkeypatch.setenv("SYSWATCH_DATABASE_URL", f"sqlite:///{database}")

    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    return config, database


def test_upgrade_creates_the_snapshots_schema(alembic_config):
    config, database = alembic_config

    command.upgrade(config, "head")

    inspector = inspect(create_engine(f"sqlite:///{database}"))
    assert "snapshots" in inspector.get_table_names()

    columns = {column["name"] for column in inspector.get_columns("snapshots")}
    assert columns == {
        "id",
        "host_name",
        "collected_at",
        "cpu_core_count",
        "cpu_usage_percent",
        "mem_total_mb",
        "mem_used_mb",
        "disk_total_gb",
        "disk_free_gb",
        "os_name",
        "os_version",
    }

    assert [i["name"] for i in inspector.get_indexes("snapshots")] == ["ix_snapshots_collected_at"]
    assert [u["name"] for u in inspector.get_unique_constraints("snapshots")] == [
        "uq_snapshots_host_name_collected_at"
    ]


def test_migrations_match_the_models(alembic_config):
    config, _ = alembic_config
    command.upgrade(config, "head")

    # Fails if the ORM models have changed without a matching migration.
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"Models and migrations have diverged: {exc}")


def test_downgrade_removes_the_table(alembic_config):
    config, database = alembic_config

    command.upgrade(config, "head")
    command.downgrade(config, "base")

    inspector = inspect(create_engine(f"sqlite:///{database}"))
    assert "snapshots" not in inspector.get_table_names()
