"""add rule silencing

Nullable, so this stays a metadata-only ALTER TABLE rather than a rewrite, and
because NULL is the honest way to say "not silenced" - a sentinel date would
need everyone reading the column to know which date meant nothing.

Revision ID: 07b9854c46b7
Revises: 494f11c51de7
Create Date: 2026-09-06 12:06:55.150747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b9854c46b7'
down_revision: Union[str, Sequence[str], None] = '494f11c51de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('silenced_until', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_column('silenced_until')

    # ### end Alembic commands ###
