"""add process and network columns

Revision ID: 1ba244015a6c
Revises: c69cb3ded3fd
Create Date: 2026-09-02 12:02:02.967463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba244015a6c'
down_revision: Union[str, Sequence[str], None] = 'c69cb3ded3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('net_bytes_sent_per_sec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('net_bytes_recv_per_sec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('process_top', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('network_interfaces', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_column('network_interfaces')
        batch_op.drop_column('process_top')
        batch_op.drop_column('net_bytes_recv_per_sec')
        batch_op.drop_column('net_bytes_sent_per_sec')
        batch_op.drop_column('process_count')

    # ### end Alembic commands ###
