"""add alert acknowledgement

Both nullable, which is not only about existing rows: an alert that nobody has
acknowledged has no time and no name to record, and NULL says that better than
a sentinel would. It also keeps this a metadata-only ALTER TABLE rather than a
table rewrite, so the upgrade stays constant-time on a database with a year of
alert history in it.

Revision ID: 494f11c51de7
Revises: b5a0aad7e429
Create Date: 2026-09-06 11:43:44.470720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494f11c51de7'
down_revision: Union[str, Sequence[str], None] = 'b5a0aad7e429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('acknowledged_by', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('acknowledged_by')
        batch_op.drop_column('acknowledged_at')

    # ### end Alembic commands ###
