"""create snapshots table

Revision ID: c69cb3ded3fd
Revises: 
Create Date: 2026-08-13 17:33:37.626269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69cb3ded3fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_name', sa.String(length=255), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_core_count', sa.Integer(), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=False),
    sa.Column('mem_total_mb', sa.Integer(), nullable=False),
    sa.Column('mem_used_mb', sa.Integer(), nullable=False),
    sa.Column('disk_total_gb', sa.Integer(), nullable=False),
    sa.Column('disk_free_gb', sa.Integer(), nullable=False),
    sa.Column('os_name', sa.String(length=255), nullable=False),
    sa.Column('os_version', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshots')),
    sa.UniqueConstraint('host_name', 'collected_at', name=op.f('uq_snapshots_host_name_collected_at'))
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshots_collected_at', ['collected_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_collected_at')

    op.drop_table('snapshots')
    # ### end Alembic commands ###
